module.exports = [
  // ── SUAVE ────────────────────────────────────────────────────────
  { texto: 'Yo nunca he mentido para salir de un compromiso', categoria: 'suave' },
  { texto: 'Yo nunca he comido directamente del bote sin usar cubiertos', categoria: 'suave' },
  { texto: 'Yo nunca he enviado un mensaje al destinatario equivocado', categoria: 'suave' },
  { texto: 'Yo nunca he fingido no haber visto un mensaje', categoria: 'suave' },
  { texto: 'Yo nunca he llorado con una película de animación', categoria: 'suave' },
  { texto: 'Yo nunca he hecho trampa en un juego de mesa', categoria: 'suave' },
  { texto: 'Yo nunca he googleado mi propio nombre', categoria: 'suave' },
  { texto: 'Yo nunca he fingido estar ocupado para no salir', categoria: 'suave' },
  { texto: 'Yo nunca he cantado en el coche como si fuera un concierto', categoria: 'suave' },
  { texto: 'Yo nunca he olvidado el cumpleaños de alguien importante', categoria: 'suave' },
  { texto: 'Yo nunca he leído el final de un libro antes de terminarlo', categoria: 'suave' },
  { texto: 'Yo nunca me he quedado dormido viendo una película', categoria: 'suave' },
  { texto: 'Yo nunca he comprado algo y luego dicho que lo tenía de antes', categoria: 'suave' },
  { texto: 'Yo nunca he cancelado planes en el último momento sin motivo real', categoria: 'suave' },

  // ── FIESTA ───────────────────────────────────────────────────────
  { texto: 'Yo nunca he vomitado en la calle de tanto beber', categoria: 'fiesta' },
  { texto: 'Yo nunca he ligado en una boda', categoria: 'fiesta' },
  { texto: 'Yo nunca he bailado encima de una silla o una mesa', categoria: 'fiesta' },
  { texto: 'Yo nunca he acabado una noche sin recordar cómo llegué a casa', categoria: 'fiesta' },
  { texto: 'Yo nunca he pedido al DJ que me pusiera una canción', categoria: 'fiesta' },
  { texto: 'Yo nunca he besado a dos personas distintas en la misma noche', categoria: 'fiesta' },
  { texto: 'Yo nunca he perdido el móvil de fiesta', categoria: 'fiesta' },
  { texto: 'Yo nunca me he quedado dormido en una fiesta', categoria: 'fiesta' },
  { texto: 'Yo nunca he ido a trabajar sin dormir tras una noche de fiesta', categoria: 'fiesta' },
  { texto: 'Yo nunca me he colado en una discoteca sin pagar', categoria: 'fiesta' },
  { texto: 'Yo nunca he hecho el "Walk of shame" a la mañana siguiente', categoria: 'fiesta' },
  { texto: 'Yo nunca he llamado a mi ex a las 3 de la mañana', categoria: 'fiesta' },
  { texto: 'Yo nunca he perdido un zapato o prenda de ropa de fiesta', categoria: 'fiesta' },
  { texto: 'Yo nunca he tenido que buscar mi coche al día siguiente porque no recordaba dónde lo dejé', categoria: 'fiesta' },

  // ── PICANTE +18 ──────────────────────────────────────────────────
  { texto: 'Yo nunca he mandado una foto comprometedora', categoria: 'picante' },
  { texto: 'Yo nunca he tenido relaciones en un sitio público', categoria: 'picante' },
  { texto: 'Yo nunca he practicado sexting', categoria: 'picante' },
  { texto: 'Yo nunca he mentido sobre el número de personas con las que he estado', categoria: 'picante' },
  { texto: 'Yo nunca he tenido una noche de una sola vez', categoria: 'picante' },
  { texto: 'Yo nunca he fantaseado con alguien de aquí presente', categoria: 'picante' },
  { texto: 'Yo nunca he visto contenido para adultos en el trabajo o en clase', categoria: 'picante' },
  { texto: 'Yo nunca he usado una aplicación de citas', categoria: 'picante' },
  { texto: 'Yo nunca he tenido una relación secreta que nadie conocía', categoria: 'picante' },
  { texto: 'Yo nunca he hecho un striptease', categoria: 'picante' },
  { texto: 'Yo nunca he roto algo durante el sexo', categoria: 'picante' },
  { texto: 'Yo nunca he fingido un orgasmo', categoria: 'picante' },
  { texto: 'Yo nunca he besado a alguien del mismo sexo', categoria: 'picante' },
  { texto: 'Yo nunca he tenido relaciones con alguien mucho mayor o menor que yo', categoria: 'picante' },
];
